{
 "title": "AliCloud Redis Detail",
 "tags": [
  "Redis",
  "Detail"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "label_values(aliyun_meta_redis_info,InstanceName)"
   },
   {
    "name": "instanceId",
    "query": "label_values(aliyun_meta_redis_info{InstanceName=\"$hostname\"},UserName)"
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aliyun_meta_redis_info{UserName=\"$instanceId\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_kvstore_MemoryUsage{instanceId=\"$instanceId\"}"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_kvstore_CpuUsage{instanceId=\"$instanceId\"}"
    }
   ]
  },
  {
   "title": "Connection Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_kvstore_ConnectionUsage{instanceId=\"$instanceId\"}"
    }
   ]
  },
  {
   "title": "Traffic Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_kvstore_IntranetInRatio{instanceId=\"$instanceId\"}",
     "legendFormat": "Rx"
    },
    {
     "expr": "aliyun_acs_kvstore_IntranetOutRatio{instanceId=\"$instanceId\"}",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_kvstore_IntranetIn{instanceId=\"$instanceId\"}",
     "legendFormat": "Rx"
    },
    {
     "expr": "aliyun_acs_kvstore_IntranetOut{instanceId=\"$instanceId\"}",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Failed Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_kvstore_FailedCount{instanceId=\"$instanceId\"}"
    }
   ]
  }
 ]
}